spring:
  datasource:
    url: jdbc:mysql://localhost/jpa_manytomany_extracolumns?useUnicode=true&amp&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true