spring:
  datasource:
    url: jdbc:mysql://localhost/jpa_onetoone_foreignkey?useUnicode=true&amp&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true